bind r source-file ~/.tmux.conf \; display-message "                                                                               --- Config Reloaded! ---"
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# main
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set -g mouse on

set-option -g allow-rename off

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel \; run-shell "tmux save-buffer - | (xsel -ib || xclip -sel clip)"
set-option -s set-clipboard external 


setw -g clock-mode-colour yellow
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=color201'

setw -g mode-style 'fg=black bg=color201'

set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=color201'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=color201'
set -g status-right '  %H:%M  '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=color201'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=color201 bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=cyan]#F '
setw -g mode-keys vi
set -g message-style 'fg=black bg=color201'
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# stop making cursor change
set -g cursor-style vertical-bar
